{"name": "test_successful_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "config = {'api_base_url': 'https://reqres.in/', 'api_base_url2': 'https://jsonplaceholder.typicode.com/'}\n\n    @allure.feature(\"Authentication\")\n    @allure.story(\"Successful login\")\n    def test_successful_login(config):\n        client = AuthClient(config[\"api_base_url\"])\n        response = client.login(\"eve.holt@reqres.in\", \"cityslicka\")\n    \n        with allure.step(\"Verify successful login\"):\n>           assert response.status_code == 200\nE           assert 404 == 200\nE            +  where 404 = <Response [404]>.status_code\n\ntests\\test_auth_api.py:12: AssertionError"}, "steps": [{"name": "Verify successful login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code\n", "trace": "  File \"C:\\Users\\n.krotsik\\Desktop\\Pytest\\automation_project_API\\tests\\test_auth_api.py\", line 12, in test_successful_login\n    assert response.status_code == 200\n"}, "start": 1746615260983, "stop": 1746615260984}], "start": 1746615260816, "stop": 1746615260984, "uuid": "6b315a17-d7a9-4308-a460-8d6326002e79", "historyId": "4893e92e518e23e3b7de348fd5509cd4", "testCaseId": "4893e92e518e23e3b7de348fd5509cd4", "fullName": "tests.test_auth_api#test_successful_login", "labels": [{"name": "story", "value": "Successful login"}, {"name": "feature", "value": "Authentication"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_api"}, {"name": "host", "value": "PLWRS-PF43AQAR"}, {"name": "thread", "value": "19952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_api"}]}