{"name": "test_successful_login", "status": "broken", "statusDetails": {"message": "KeyError: 'api_base_url'", "trace": "config = {'allure': {'build_name': 'Local Test Run', 'build_order': '1', 'executor_name': 'Local Machine', 'report_name': 'API ...'}, 'default_headers': {'Accept': 'application/json', 'Content-Type': 'application/json'}, 'environment': 'Local', ...}\n\n    @allure.feature(\"Authentication\")\n    @allure.story(\"Successful login\")\n    def test_successful_login(config):\n>       client = AuthClient(config[\"api_base_url\"])\nE       KeyError: 'api_base_url'\n\ntests\\test_auth_api.py:8: KeyError"}, "start": 1747038420268, "stop": 1747038420268, "uuid": "aecd543b-f960-4f18-886c-078d715afcff", "historyId": "4893e92e518e23e3b7de348fd5509cd4", "testCaseId": "4893e92e518e23e3b7de348fd5509cd4", "fullName": "tests.test_auth_api#test_successful_login", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "story", "value": "Successful login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_api"}, {"name": "host", "value": "PLWRS-PF43AQAR"}, {"name": "thread", "value": "17196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_api"}]}